language: node_js
node_js: 6.3.0

script:
  - cp -r source/ build/

-: &deploy
  provider: s3
  bucket: dash-connect-site
  region: eu-west-1
  acl: public_read
  local_dir: build/
  skip_cleanup: true
  cache_control: public, max-age=60 # TODO: Set multiple values
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_KEY_SECRET
  on: { all_branches: true }

deploy:
  - <<: *deploy
    upload_dir: versions/commit/$TRAVIS_COMMIT
  - <<: *deploy
    upload_dir: versions/branch/$TRAVIS_BRANCH
    on: { all_branches: true, tags: false }
  - <<: *deploy
    upload_dir: versions/tag/$TRAVIS_TAG
    on: { tags: true }

notifications:
  email: false
  slack: $SLACK_KEY
