language: node_js
node_js: 6.2.2

script:
  - cp -r source/ build/

deploy:
  - provider: s3
    bucket: dash-connect-site
    region: eu-west-1
    acl: public_read
    local_dir: build/
    skip_cleanup: true
    cache_control: public, max-age=86400
    access_key_id:
      secure: L6qEpG9agtTVTeZtGbVZGhGSnOnObVxAkNMYdEKxtf2QJUsBAmeMqaYuLQbVpjLlyMQaMETY20PEySX1VfEsmV7Cfd+iVMEzBhYLr4srXYkydUvMPiGHvrW/XmLBwwJj7eviGCOKnuJdYw2VEXtsZ7JBKg7jw+2f3+w1RnnCXII3VbkIBeOlc30Yl6qylOqaYXBvdosRrFZgcmcIO+d/sOqyHHTC9VSJWVPQx26f3yISr1y4kEPt6wIKWL9GMk5/Clo4ShBebboEJgno67KTfG3wMES6fb4UgHocC6+FVXOFlGDuYNBC8EseGj/COWO3W9I9PVyejZiqxkJMCHDiEvLvSat/UpjgcV9EmF89IexT92Ey58FHOx94L40k4yDXYw7vV/B8nceDOkgnMEokCwGMw5HuvWVBvyl3+KLyshUT9xASAneQNb1XFzPk7YlPEUhHpkouDG0xyXO4O/YN5d/Rq21gf0ALxPYZJOd17wsYOfv22NtSNGglulMT1fRHJrFPXURYHY+yI6I32QjGQJEbIeI65iLy8pvltgbwSllHrL0gC9txwJnNOyQyxRTASpy7+7nrZ0uABNYiyAcnJ6KXItEQszK32mSTK0kCbmLvUxC/cDF5DMFJuin+84+qxjjyrMbD7E5tEKJy+mYjMHGvKkaiB5jPnBjQoYUwUK4=
    secret_access_key:
      secure: sByzqoY8vr4PvORQYc/hd8ovuZCg06LhhcJ5NN67Jifz5bEVR2ZTvzfvwrF2xqYJFa37ZL4wAr6IxoA7nI6cJEWugBdhuKg18nn6C79EqiBnFtk8G6yB7/iwps/42ilfOkYDw6HbD3AY0iEsNZwz30EbeUT4ktAXEyvEIle/fn3jVj/SD0cnXsftdQcgFWnkbQXMRvGgkkkDyFS2lqhP9SlikSbWlY/auBWiU3DlW3n2iTfqwOtBVnn+jy4soLc9yBevgYU4uzbv015ULdG/QUn2K13khZdc9fRXoJxvh7gpe/pT8AjsfLTOUe2dW0xQOzd9jybpzWBxipVi23X5tb16oj12iKQwEQYGv1GOfWVauewaTvpTP1lKii3+9i+5JecvUg0oWaaCCtIpeVPxH5gOKzTlJH21QR8thwo6+svCqq0Fqw4Gx8CpmreUg3oGE+ffJ/hTY8nDpZN/jZ1oLIv0SPJTu3pr61gMTtQXQYuMw5lBUrh8QFknG2Ip4Ykq/mcfnS3bTqYhPqNUSVTmXQzYFkP6HIFOs4KJ8ddAtbHlEooly1YzV5Y1aP55aL1sRhTolOsiDl16ZR3/uTY69/eMImlbT33+z3HXlfw0W+zxqy1K26BTXPidCsoaKmh7TOei7A14UE4KwAlOSX/MnZz774eBIrwBlFxQ+XXxiMA=

notifications:
  email: false
